spring.application.name=loan-management
server.port=8080

# MySQL JDBC configuration
spring.datasource.url=jdbc:mysql://localhost:3306/beneficiary_loan_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JDBC settings
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

# Logging
logging.level.org.springframework=INFO
logging.level.com.saisidharth.loanmanagement=DEBUG
